[path]
master_log_file = "logs/master.log"
prog_log_file = "logs/prog.log"
data_header = "data/"


[NIDigital]
deviceID = "PXI1Slot8"
pinmap = "settings/DEC3_ProbeCard_CNFET_8x8.pinmap"
specs = [
    "settings/DEC3.specs",
    "settings/DEC3_ProbeCard_levels_8x8.digilevels",
    "settings/DEC3.digitiming",
]
patterns = "settings/patterns/*DEC3_probecard_8x8.digipat"


[device]
# define all body voltage names and map them to their neutral value
# for PMOS this is typically VDD while for NMOS this is typically GND or VSS
# body = { A2_PMOS_BODY = 1.5, A2_NMOS_BODY = 0.0 }
# body = { A2_PMOS_BODY = 0.0, A2_NMOS_BODY = 0.0 }
body = {} # for cnfet

# define all WLs, BLs, SLs names
all_WLS = [ "A8_WL_0", "A8_WL_1", "A8_WL_2", "A8_WL_3", "A8_WL_4", "A8_WL_5", "A8_WL_6", "A8_WL_7" ]
all_BLS = [ "A8_BL_0", "A8_BL_1", "A8_BL_2", "A8_BL_3", "A8_BL_4", "A8_BL_5", "A8_BL_6", "A8_BL_7" ]
all_SLS = [ "A8_SL_0", "A8_SL_1", "A8_SL_2", "A8_SL_3", "A8_SL_4", "A8_SL_5", "A8_SL_6", "A8_SL_7" ]

# subset of WL, BL, SL that will be pulsed for measurement
# all BL,WL,SL targeting set
# WLS = [ "A8_WL_0", "A8_WL_2", "A8_WL_4", "A8_WL_6" ]
# BLS = [ "A8_BL_0", "A8_BL_2", "A8_BL_4", "A8_BL_6" ]
# SLS = [ "A8_SL_0", "A8_SL_2", "A8_SL_4", "A8_SL_6" ]

# all BL,WL,SL targeting reset
# WLS = [ "A8_WL_1", "A8_WL_3", "A8_WL_5", "A8_WL_7" ]
# BLS = [ "A8_BL_1", "A8_BL_3", "A8_BL_5", "A8_BL_7" ]
# SLS = [ "A8_SL_1", "A8_SL_3", "A8_SL_5", "A8_SL_7" ]

#targeting read
# WLS = [ "A8_WL_0", "A8_WL_1", "A8_WL_2", "A8_WL_3", "A8_WL_4", "A8_WL_5", "A8_WL_6", "A8_WL_7" ]
# BLS = [ "A8_BL_0", "A8_BL_1", "A8_BL_2", "A8_BL_3", "A8_BL_4", "A8_BL_5", "A8_BL_6", "A8_BL_7" ]
# SLS = [ "A8_SL_0", "A8_SL_1", "A8_SL_2", "A8_SL_3", "A8_SL_4", "A8_SL_5", "A8_SL_6", "A8_SL_7" ]


# WLS = [ "A8_WL_0"] #, "A8_WL_1" ]
# BLS = [ "A8_BL_2"] #, "A8_BL_1" ]
# SLS = [ "A8_SL_2"] #, "A8_SL_1" ]

# uncomment for testing single cell
WLS = [ "A8_WL_3" ]
BLS = [ "A8_BL_3" ]
SLS = [ "A8_SL_3" ]


# RRAM resistance target level corresponding to each operation defined below
# [target_res]
# FORM = 40000
# SET = 40000
# RESET = 150000

# for cnfet
[target_res]
FORM = 50000
SET = 12000
RESET = 20000

# =============================================================================
# MEASUREMENT OPERATION (OP) CONFIGS
# format of op configs:
#   [op.NAME]
#   ### common properties here
#   [op.NAME.NMOS]
#   ### NMOS specific voltage/pulse values
#   [op.NAME.PMOS]
#   ### PMOS specific voltage/pulse values

# =============================================================================
# READ PULSE
# =============================================================================
[op.READ]
mode = "digital"
aperture_time = 0.0005
current_limit_range = 0.000032
relaxation_cycles = 100
settling_time = 0.0001
shunt_res_value = 0

[op.READ.NMOS]
VWL = 1.5
VBL = 0.3
VSL = 0
VB = 0

[op.READ.PMOS]
VWL = -0.3
VBL = -0.3
VSL = 0
VB = 1.5

# =============================================================================
# FORM PULSE
# =============================================================================
[op.FORM]
settling_time = 0.0001

[op.FORM.NMOS]
VWL = 1.8
VBL = 2
VSL = 0
PW = 1200

VWL_SET_start = 1.0
VWL_SET_step = 0.2
VWL_SET_stop = 2.2

VBL_start = 0.5
VBL_step = 0.2
VBL_stop = 4.5

PW_start = 1
PW_stop = 1000
PW_steps = 3

[op.FORM.PMOS]
VWL = 1.5
VBL = 1
VSL = 2
PW = 1200

VWL_SET_start = 1.7
VWL_SET_step = -0.1
VWL_SET_stop = 1.0

VBL_start = 1
VBL_step = -0.1
VBL_stop = -1

PW_start = 1
PW_stop = 1000
PW_steps = 4

# =============================================================================
# SET PULSE
# =============================================================================
[op.SET]
settling_time = 0.001

[op.SET.NMOS]
VWL = 0.5
VBL = 0.5
VSL = 0
PW = 1

VWL_SET_start = 0.5
VWL_SET_step = 0.1
VWL_SET_stop = 1.5

VBL_start = 0.5
VBL_step = 0.1
VBL_stop = 2.0

PW_start = 1
PW_stop = 100
PW_steps = 4

[op.SET.PMOS]
VWL = 0.5
VBL = 1
VSL = 2
PW = 1200

VWL_SET_start = 1.7
VWL_SET_step = -0.1
VWL_SET_stop = 1.0

VBL_start = 1
VBL_step = -0.1
VBL_stop = -0.5

PW_start = 1
PW_stop = 1000
PW_steps = 4

# =============================================================================
# RESET PULSE
# =============================================================================
[op.RESET]
settling_time = 0.001

[op.RESET.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 1

VWL_RESET_start = 3.5
VWL_RESET_step = 0.2
VWL_RESET_stop = 4

VSL_start = 3.8
VSL_step = 0.2
VSL_stop = 5.5

PW_start = 1
PW_stop = 1000
PW_steps = 2

[op.RESET.PMOS]
VWL = 1.1
VSL = 1.5
VBL = 2.5
PW = 100

VWL_RESET_start = 1.1
VWL_RESET_step = -0.2
VWL_RESET_stop = -0.5

VSL_start = 1.5
VSL_step = -0.2
VSL_stop = 0.0

PW_start = 1
PW_stop = 1000
PW_steps = 2
