[path]
master_log_file = "logs/master.log"
prog_log_file = "logs/prog.log"
data_header = "data/"


[NIDigital]
deviceID = "PXI1Slot7"
pinmap = "settings/DEC3_ProbeCard_Full_SiFET.pinmap"
specs = [
    "settings/DEC3.specs",
    "settings/DEC3_Full_SiFET.digilevels",
    "settings/DEC3.digitiming",
]
patterns = "settings/patterns/*DEC3_Full_SiFET_2x2.digipat"


[device]
# define all body voltage names and map them to their neutral value
# for PMOS this is typically VDD while for NMOS this is typically GND or VSS
# body = { A2_PMOS_BODY = 1.5, A2_NMOS_BODY = 0.0 }
# body = { A2_PMOS_BODY = 0.0, A2_NMOS_BODY = 0.0 }
body = {} # for cnfet

# define all WLs, BLs, SLs names
all_WLS = [ "A2_WL_0", "A2_WL_1" ]
all_BLS = [ "A2_BL_0", "A2_BL_1" ]
all_SLS = [ "A2_SL_0", "A2_SL_1" ]

# subset of WL, BL, SL that will be pulsed for measurement
# all BL,WL,SL
WLS = [ "A2_WL_0", "A2_WL_1" ]
BLS = [ "A2_BL_0", "A2_BL_1" ]
SLS = [ "A2_SL_0", "A2_SL_1" ]

# uncomment for testing single cell
# WLS = [ "A2_WL_0" ]
# BLS = [ "A2_BL_0" ]
# SLS = [ "A2_SL_0" ]


# RRAM resistance target level corresponding to each operation defined below
# [target_res]
# FORM = 40000
# SET = 40000
# RESET = 150000

# for cnfet
[target_res]
FORM = 5000
SET = 5000
RESET = 20000

# =============================================================================
# MEASUREMENT OPERATION (OP) CONFIGS
# format of op configs:
#   [op.NAME]
#   ### common properties here
#   [op.NAME.NMOS]
#   ### NMOS specific voltage/pulse values
#   [op.NAME.PMOS]
#   ### PMOS specific voltage/pulse values

# =============================================================================
# READ PULSE
# =============================================================================
[op.READ]
mode = "digital"
aperture_time = 0.0005
current_limit_range = 0.000032
relaxation_cycles = 100
settling_time = 0.0001
shunt_res_value = 0

[op.READ.NMOS]
VWL = 1.5
VBL = 0.3
VSL = 0
VB = 0

[op.READ.PMOS]
VWL = -1.5
VBL = -0.3
VSL = 0
VB = 1.5

# =============================================================================
# FORM PULSE
# =============================================================================
[op.FORM]
settling_time = 0.001

[op.FORM.NMOS]
VWL = 1.8
VBL = 2
VSL = 0
PW = 1200

VWL_SET_start = 0.5
VWL_SET_step = 0.1
VWL_SET_stop = 1.5

VBL_start = 0.5
VBL_step = 0.1
VBL_stop = 2.2

PW_start = 1
PW_stop = 1000
PW_steps = 4

[op.FORM.PMOS]
VWL = 0.5
VBL = 0
VSL = 2
PW = 1200

VWL_SET_start = 1
VWL_SET_step = -0.1
VWL_SET_stop = -0.5

VBL_start = 1
VBL_step = -0.1
VBL_stop = -2

PW_start = 1
PW_stop = 1000
PW_steps = 4

# =============================================================================
# SET PULSE
# =============================================================================
[op.SET]
settling_time = 0.001

[op.SET.NMOS]
VWL = 0
VBL = 2
VSL = 0
PW = 100

VWL_SET_start = 0.5
VWL_SET_step = 0.1
VWL_SET_stop = 1.5

VBL_start = 0.5
VBL_step = 0.1
VBL_stop = 2.0

PW_start = 1
PW_stop = 100
PW_steps = 3

[op.SET.PMOS]
VWL = 0.5
VBL = 0
VSL = 2
PW = 1200

VWL_SET_start = 1
VWL_SET_step = -0.1
VWL_SET_stop = -0.5

VBL_start = 1
VBL_step = -0.1
VBL_stop = -1

PW_start = 1
PW_stop = 1000
PW_steps = 4

# =============================================================================
# RESET PULSE
# =============================================================================
[op.RESET]
settling_time = 0.001

[op.RESET.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100

VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5

VSL_start = 2
VSL_step = 0.2
VSL_stop = 5

PW_start = 1
PW_stop = 1000
PW_steps = 3

[op.RESET.PMOS]
VWL = -1
VSL = 1.5
VBL = 2.5
PW = 100

VWL_RESET_start = 0.4
VWL_RESET_step = -0.2
VWL_RESET_stop = -2.0

VSL_start = 1.0
VSL_step = -0.1
VSL_stop = -2.0

PW_start = 1
PW_stop = 1000
PW_steps = 3
