[path]
master_log_file = "logs/master.log"
prog_log_file = "logs/prog.log"
data_header = "data/"


[NIDigital]
deviceID = "PXI1Slot9"
pinmap = "settings/MPW.pinmap"
specs = [
  "settings/DEC3.specs",
  "settings/DEC3.digilevels",
  "settings/DEC3.digitiming"
]
patterns = "settings/patterns/*DEC3.digipat"


[device]
# define all body voltage names and map them to their neutral value
# for PMOS this is typically VDD while for NMOS this is typically GND or VSS
body = { Body = 0.0 }

# define all WLs, BLs, SLs names
all_WLS = [ "WL_0", "WL_1", "WL_2", "WL_3" ]
all_BLS = [ "BL_0", "BL_1", "BL_2", "BL_3" ]
all_SLS = [ "SL_0", "SL_1", "SL_2", "SL_3" ]

# subset of WL, BL, SL that will be pulsed for measurement
WLS = [ "WL_0" ]
BLS = [ "BL_0" ]
SLS = [ "SL_0" ]


# RRAM resistance target level corresponding to each operation defined below
[target_res]
FORM = 40000
SET = 25000
RESET = 100000

# =============================================================================
# MEASUREMENT OPERATION (OP) CONFIGS
# format of op configs:
#   [op.NAME]
#   ### common properties here
#   [op.NAME.NMOS]
#   ### NMOS specific voltage/pulse values
#   [op.NAME.PMOS]
#   ### PMOS specific voltage/pulse values

# =============================================================================
# READ PULSE
# =============================================================================
[op.READ]
mode = "digital"
aperture_time = 0.0005
current_limit_range = 0.000032
relaxation_cycles = 100
settling_time = 0.000001
shunt_res_value = 0

[op.READ.NMOS]
VWL = 1.5
VBL = 0.2
VSL = 0
VB = 0

[op.READ.PMOS]
VWL = -1.3
VBL = 0
VSL = 0.2
VB = 1.5

# =============================================================================
# FORM PULSE
# =============================================================================
[op.FORM.NMOS]
VWL = 1.8
VBL = 3
VSL = 0
PW = 1200
VWL_SET_start = 1
VWL_SET_step = 0.3
VWL_SET_stop = 2.5
VBL_start = 1
VBL_step = 0.5
VBL_stop = 3.5
PW_start = 1
PW_stop = 1_000
PW_steps = 4

[op.FORM.PMOS]
VWL = 0.5
VBL = 0
VSL = 2
PW = 1200
VWL_SET_start = 1
VWL_SET_step = -0.1
VWL_SET_stop = -0.5
VBL_start = 1
VBL_step = -0.1
VBL_stop = -2
PW_start = 1
PW_stop = 1_000
PW_steps = 4

# =============================================================================
# SET PULSE
# =============================================================================
[op.SET.NMOS]
VWL = 0
VBL = 4
VSL = 0
PW = 100
VWL_SET_start = 1.2
VWL_SET_step = 0.4
VWL_SET_stop = 2.4
VBL_start = 1.5
VBL_step = 0.5
VBL_stop = 3
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.SET.PMOS]
VWL = 0.5
VBL = 0
VSL = 2
PW = 1200
VWL_SET_start = 1
VWL_SET_step = -0.1
VWL_SET_stop = -0.5
VBL_start = 1
VBL_step = -0.1
VBL_stop = -1
PW_start = 1
PW_stop = 1_000
PW_steps = 4

# =============================================================================
# RESET PULSE
# =============================================================================
[op.RESET.NMOS]
VWL = 2.5
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 1.9
VSL_start = 0.0
VSL_step = -0.2
VSL_stop = -1.0
PW_start = 1
PW_stop = 1_000
PW_steps = 4

[op.RESET.PMOS]
VWL = -1
VSL = 1.5
VBL = 2.5
PW = 100
VWL_RESET_start = 0.5
VWL_RESET_step = -0.1
VWL_RESET_stop = -0.5
VSL_start = 2
VSL_step = -0.1
VSL_stop = 0.5
PW_start = 1
PW_stop = 100
PW_steps = 3

