[path]
master_log_file = "logs/master.log"
prog_log_file = "logs/prog.log"
data_header = "data/"


[NIDigital]
deviceID = "PXI1Slot9"
pinmap = "settings/MPW_ProbeCard.pinmap"
specs = [
  "settings/DEC3.specs",
  "settings/MPW_ProbeCard.digilevels",
  "settings/MPW_ProbeCard.digitiming"
]
patterns = "settings/patterns/*MPW_ProbeCard.digipat"


[device]
# define all body voltage names and map them to their neutral value
# for PMOS this is typically VDD while for NMOS this is typically GND or VSS
body = { Body = 0.0 }

# define all WLs, BLs, SLs names
all_WLS = [
  "WL_0",
  "WL_2",
  "WL_4",
  "WL_6",
  "WL_8",
  "WL_10",
  "WL_12",
  "WL_14"
]
all_BLS = [
  "BL_8",
  "BL_9",
  "BL_10",
  "BL_11",
  "BL_12",
  "BL_13",
  "BL_14",
  "BL_15"
]
all_SLS = [
  "SL_8",
  "SL_9",
  "SL_10",
  "SL_11",
  "SL_12",
  "SL_13",
  "SL_14",
  "SL_15"
]
relays = [
  "WL_14",
  "WL_12",
  "WL_10",
  "WL_8",
  "WL_6",
  "WL_4",
  "WL_2",
  "WL_0"
]

# subset of WL, BL, SL that will be pulsed for measurement
WLS = [ "WL_6" ]
BLS = [ "BL_12" ]
SLS = [ "SL_12" ]
WL_UNSEL = [ "WL_UNSEL" ]


# RRAM resistance target level corresponding to each operation defined below
[target_res]
FORM = 20_000
SET = 20_000
RESET_0 = 60_000
RESET_1 = 120_000
RESET_2 = 190_000
RESET_3 = 170_000
RESET_4 = 210_000
RESET_5 = 250_000
RESET_6 = 290_000
RESET_7 = 330_000
RESET = 100_000

# =============================================================================
# MEASUREMENT OPERATION (OP) CONFIGS
# format of op configs:
#   [op.NAME]
#   ### common properties here
#   [op.NAME.NMOS]
#   ### NMOS specific voltage/pulse values
#   [op.NAME.PMOS]
#   ### PMOS specific voltage/pulse values

# =============================================================================
# READ PULSE
# =============================================================================
[op.READ]
mode = "digital"
aperture_time = 0.0005
current_limit_range = 0.000128
relaxation_cycles = 1_000
settling_time = 0.00001
shunt_res_value = 0

[op.READ.NMOS]
VWL = 1.5
VBL = 0.2
VSL = 0
VWL_UNSEL = 0
VB = 0

[op.READ.PMOS]
VWL = -1.2
VBL = -0.3
VSL = 0
VLW_UNSEL = 0.5
VB = 0

# =============================================================================
# FORM PULSE
# =============================================================================
[op.FORM.NMOS]
VWL = 1.8
VBL = 3
VSL = 0
VWL_UNSEL = 0
PW = 1200
VWL_SET_start = 1
VWL_SET_step = 0.1
VWL_SET_stop = 2.5
VBL_start = 1
VBL_step = 0.1
VBL_stop = 3.5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.FORM.PMOS]
VWL = 0.5
VBL = 0
VSL = 0.5
VWL_UNSEL = 1
PW = 1200
VWL_SET_start = 0.5
VWL_SET_step = -0.1
VWL_SET_stop = -1.2
VBL_start = 2
VBL_step = -0.1
VBL_stop = -2
PW_start = 1
PW_stop = 1_000
PW_steps = 3

# =============================================================================
# SET/RESET PULSE
# =============================================================================
[op.SET.NMOS]
VWL = 0
VBL = 4
VSL = 2
VWL_UNSEL = 2
PW = 100
VWL_SET_start = 1.2
VWL_SET_step = 0.1
VWL_SET_stop = 2.2
VBL_start = 1.5
VBL_step = 0.1
VBL_stop = 2.5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.SET.PMOS]
VWL = 0.5
VBL = 0
VSL = 0.5
VWL_UNSEL = 0.5
PW = 1000
VWL_SET_start = 0
VWL_SET_step = -0.1
VWL_SET_stop = -0.7
VBL_start = 0
VBL_step = -0.1
VBL_stop = -1.3
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
VWL_UNSEL = 3
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
VWL_UNSEL = 0.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 2
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_0.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_0.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_1.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_1.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_2.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_2.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_3.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_3.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_4.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_4.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_5.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_5.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_6.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_6.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_7.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_7.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 100
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 1.5
VSL_step = -0.1
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_SWEEP.NMOS]
VWL = 2.5
VSL = 3
VBL = 0
PW = 100
PCOUNT = 1
VWL_RESET_start = 1.8
VWL_RESET_step = 0.1
VWL_RESET_stop = 2.5
VSL_start = 2
VSL_step = 0.2
VSL_stop = 5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.RESET_SWEEP.PMOS]
VWL = -1
VSL = 0
VBL = 2.5
PW = 200
PCOUNT = 3
VWL_RESET_start = -1
VWL_RESET_step = -0.1
VWL_RESET_stop = -1.8
VSL_start = 2.5
VSL_step = -0.01
VSL_stop = 0
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.SET_SWEEP.NMOS]
VWL = 0
VBL = 4
VSL = 2
PW = 100
VWL_SET_start = 1.2
VWL_SET_step = 0.1
VWL_SET_stop = 2.2
VBL_start = 1.5
VBL_step = 0.1
VBL_stop = 2.5
PW_start = 1
PW_stop = 100
PW_steps = 3

[op.SET_SWEEP.PMOS]
VWL = 0.5
VBL = 0
VSL = 0.7
PW = 200
PCOUNT = 3
VWL_SET_start = 0
VWL_SET_step = -0.1
VWL_SET_stop = -0.7
VBL_start = 0
VBL_stop = -2
VBL_step = -0.01
PW_start = 1
PW_stop = 100
PW_steps = 3
